version: '2' 
services:
  php:
    build: ./docker-php 
    working_dir: /var/www/laravel 
    volumes:
      - ./:/var/www/laravel

  nginx:
    build: ./docker-nginx
    working_dir: /var/www/laravel 
    volumes_from:
      - php 
    ports:
      - 80:80 

  database:
    image: mysql:5.7

    environment:
      - MYSQL_DATABASE=informatic_DB 
      - MYSQL_USER=if_coop
      - MYSQL_PASSWORD=admin@coop2020
      - MYSQL_ROOT_PASSWORD=admin@coop2020
    ports:
        - "3306:3306" 

  composer: 
    build: ./docker-php 
    working_dir: /var/www/laravel
    volumes_from:
      - php
    command: "composer install" 


  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
        - 8890:80
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=database
    restart: always
    depends_on:
        - database
